### ISSUE TITLE
Print object

### ISSUE THREAD

**Issue by mvpgomes** [mvpgomes/PAva-2015#27]
- If the tensor is a scalar, print its single element.
- If the tensor is a vector, print its elements on the same line separated by one white space.
- If the tensor is a matrix, print its rows as if they were vectors, separated by one empty line.
- If the tensor is not one of the previous cases, then for each sub-tensor of the first dimension, prints the sub-tensor separated from the next sub-tensor by a number of empty lines that is equal to the number of dimensions minus one.

**Comment by afpr252** [comment]
Partially implemented. The output is still not as desired.
